# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.IntegerField()),
                ('fat', models.FloatField()),
                ('carb', models.FloatField()),
                ('sugar', models.FloatField()),
                ('protein', models.FloatField()),
                ('sodium', models.FloatField()),
                ('vA', models.FloatField()),
                ('vC', models.FloatField()),
                ('iron', models.FloatField()),
                ('calcium', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritrack.Meal'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutritrack.Nutrient'),
        ),
    ]
