# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritrack', '0003_mealreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='calcium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='carb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='kcal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='vA',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='vC',
            field=models.FloatField(default=0),
        ),
    ]
