# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritrack', '0005_meal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(to='nutritrack.Ingredient'),
        ),
    ]
