# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutritrack', '0007_auto_20171028_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0)),
                ('height', models.FloatField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('activity_level', models.IntegerField(choices=[(0, 'sedentary'), (1, 'lightly active'), (2, 'moderately active'), (3, 'pretty active'), (4, 'extraordinarily active')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
