# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritrack', '0009_auto_20171029_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='servings',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='mealreport',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, default=170),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, default=60),
        ),
    ]
